## fQ-LCDM-bg.yml
# smc-stan configuration file for f(Q) = Q + α*sqrt(M)

### Sampler configuration
# The names of the parameters
# Must match the names defined in the stan model file!
names: [h, Omega_m, alpha]

# The labels to show in the plots and tables, for each parameter.
# Defaults to the name of each parameter if not provided.
# Latex is supported (dollar sign not required).
labels: [h, \Omega_m, \alpha]

# Initial condition for each parameter, for each walker.
# The most relevant initial conditions available are:
# - gauss(mu, sigma)
# - uniform(a, b)
# - float(a)
initial:
  h: gauss(0.7, 0.15)
  Omega_m: gauss(0.284, 0.1)
  alpha: uniform(-2*6**0.5, 10)

# Line markers to show rendered in the plots.
# These are optional and can be used to represent the true or expected values.
markers:
  h: 0.7
  Omega_m: 0.284
  alpha: 0

# Number of steps to sample the posterior distribution, after the warmup.
samples: 2500

# Number of steps to warmup each chain, which will be discarded.
warmup: 1000

# Number of chains to run.
# Defaults to all available hardware threads.
# Will run in parallel or sequentially based on the number of available threads.
# Keep in mind that each chain will do a total number of steps = warmup + samples.
chains: 4


### Model selection criteria
# Compute the Pareto-smoothed importance sampling leave-one-out cross-validation.
# Theory available at https://arxiv.org/abs/1507.04544 and https://arxiv.org/abs/1507.02646
PSIS-LOO-CV: false

# Compute the Watanabe–Akaike information criterion.
# Theory available at https://arxiv.org/abs/1507.04544 and https://arxiv.org/abs/1004.2316
WAIC: false

# Compute the Akaike information criterion.
AIC: false

# Compute the Bayesian information criterion.
BIC: false

# Compute the deviance information criterion.
DIC: false


### Output configuration
# Overwrite existing files, if they exist
overwrite: false

# Saves the chain to disk, in HDF5.
save-chain: true

# Compress the chain, using LZF.
compress: false

# Don't show plots on screen.
# Useful for remote connections and/or unattended runs.
hide-plots: true
